name: Deploy LLM Agent
on:
  push:
    paths:
      - 'llm-agent/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and push to Digital Ocean Registry
        env:
          DO_REGISTRY_TOKEN: ${{ secrets.DO_REGISTRY_TOKEN }}
        run: |
          cd llm-agent
          docker login registry.digitalocean.com -u ${{ secrets.DO_REGISTRY_TOKEN }} -p ${{ secrets.DO_REGISTRY_TOKEN }}
          docker build -t registry.digitalocean.com/your-registry/llm-agent:latest .
          docker push registry.digitalocean.com/your-registry/llm-agent:latest
      - name: Deploy to App Platform
        uses: digitalocean/app-action@v1
        with:
          app_name: llm-agent
          token: ${{ secrets.DO_APP_PLATFORM_TOKEN }}